[general]

#### Address & Root dir
host = "0.0.0.0"
port = 5555
root = "/var/www"

#### Cache Control headers
cache-control-headers = false

#### Auto Compression
compression = true

#### Logging
log-level = "info"

#### Security headers
security-headers = true

#### Directoy listing
directory-listing = false

#### Worker threads
threads-multiplier = 1

#### Grace period after a graceful shutdown
grace-period = 2

#### Log request Remote Address if available
log-remote-address = false

[advanced]

[[advanced.headers]]
source = "/playwright/*"

headers = { Cross-Origin-Opener-Policy = "same-origin", Cross-Origin-Resource-Policy = "same-origin", Content-Security-Policy = "frame-ancestors *" }
